// This file was autogenerated by /Users/sadovsky/dev/tadue/third_party/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../js/base.js', ['tadue.base'], []);
goog.addDependency('../../../../js/change-password.js', ['tadue.changePassword'], ['tadue.form']);
goog.addDependency('../../../../js/form.js', ['tadue.form'], []);
goog.addDependency('../../../../js/login.js', ['tadue.login'], ['tadue.form']);
goog.addDependency('../../../../js/payments.js', ['tadue.payments'], []);
goog.addDependency('../../../../js/request-payment.js', ['tadue.requestPayment'], ['goog.ui.ac.ArrayMatcher', 'goog.ui.ac.AutoComplete', 'goog.ui.ac.InputHandler', 'goog.ui.ac.Renderer', 'tadue.form', 'tadue.login', 'tadue.signup']);
goog.addDependency('../../../../js/reset-password.js', ['tadue.resetPassword'], ['tadue.form']);
goog.addDependency('../../../../js/settings.js', ['tadue.settings'], ['tadue.form']);
goog.addDependency('../../../../js/signup.js', ['tadue.signup'], ['tadue.form']);
