application: tadue-prod
version: 1
runtime: go
api_version: go1

handlers:
- url: /admin/.*
  script: _go_app
  login: admin
- url: /dev/.*
  script: _go_app
  login: admin
- url: /tasks/.*
  script: _go_app
  login: admin
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /static
  static_dir: static
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /.*
  script: _go_app
