application: tadue-prod
version: 2
runtime: go
api_version: go1

skip_files:
- ^app/config_.*.go
- ^misc/
- ^tools/

handlers:
- url: /admin/.*
  script: _go_app
  login: admin

- url: /dev/.*
  script: _go_app
  login: admin

- url: /tasks/.*
  script: _go_app
  login: admin

- url: /css
  static_dir: public/css

- url: /js
  static_dir: public/js

- url: /third_party
  static_dir: third_party

- url: /static
  static_dir: public/static

- url: /favicon.ico
  static_files: public/static/favicon.ico
  upload: public/static/favicon\.ico

- url: /.*
  script: _go_app
